<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>true</ImplicitUsings>
    <AssemblyName>ForwardChanges</AssemblyName>
    <PackageId>ForwardChanges.Standalone</PackageId>
    <RootNamespace>ForwardChanges.App</RootNamespace>
    <ApplicationIcon />
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ForwardChanges\ForwardChanges.csproj" />
    <PackageReference Include="Mutagen.Bethesda.Skyrim" Version="0.54.4" />
    <PackageReference Include="Mutagen.Bethesda.Synthesis" Version="0.36.6" />
  </ItemGroup>
</Project>
